---
abstract: 'Yet another yet another SQL builder'
author:
  - unknown
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Format
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  SQL::Format:
    file: lib/SQL/Format.pm
    version: 0.08
requires:
  perl: 5.008001
resources:
  bugtracker: http://github.com/xaicron/p5-SQL-Format/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/xaicron/p5-SQL-Format
version: 0.08
